//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xomorod.Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class local_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal local_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xomorod.Demo.Resources.local_Resources", typeof(local_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/angular-cookies.min.js.
        /// </summary>
        internal static string angular_cookies_min_js {
            get {
                return ResourceManager.GetString("angular_cookies_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/angular-marked.js.
        /// </summary>
        internal static string angular_marked_js {
            get {
                return ResourceManager.GetString("angular_marked_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/angular-1.4.7.min.js.
        /// </summary>
        internal static string angular_min_js {
            get {
                return ResourceManager.GetString("angular_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/angular-translate-loader-url-2.8.1.min.js.
        /// </summary>
        internal static string angular_translate_loader_url_min_js {
            get {
                return ResourceManager.GetString("angular_translate_loader_url_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/angular-translate-2.8.1.min.js.
        /// </summary>
        internal static string angular_translate_min_js {
            get {
                return ResourceManager.GetString("angular_translate_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/local_resources/animate-3.4.0.min.css.
        /// </summary>
        internal static string animate_min_css {
            get {
                return ResourceManager.GetString("animate_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/app.js.
        /// </summary>
        internal static string app_js {
            get {
                return ResourceManager.GetString("app_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/local_resources/bootstrap-3.3.5.min.css.
        /// </summary>
        internal static string bootstrap_min_css {
            get {
                return ResourceManager.GetString("bootstrap_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/bootstrap-3.3.5.min.js.
        /// </summary>
        internal static string bootstrap_min_js {
            get {
                return ResourceManager.GetString("bootstrap_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/local_resources/bootstrap-toggle-2.2.0.min.css.
        /// </summary>
        internal static string bootstrap_toggle_min_css {
            get {
                return ResourceManager.GetString("bootstrap_toggle_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/bootstrap-toggle-2.2.0.min.js.
        /// </summary>
        internal static string bootstrap_toggle_min_js {
            get {
                return ResourceManager.GetString("bootstrap_toggle_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/favicon.jpg.
        /// </summary>
        internal static string favicon_jpg {
            get {
                return ResourceManager.GetString("favicon_jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/local_resources/font-awesome-4.4.0.min.css.
        /// </summary>
        internal static string font_awesome_min_css {
            get {
                return ResourceManager.GetString("font_awesome_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/jquery.easing-1.3.min.js.
        /// </summary>
        internal static string jquery_easing_min_js {
            get {
                return ResourceManager.GetString("jquery_easing_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/jquery.fittext-1.1.min.js.
        /// </summary>
        internal static string jquery_fittext_min_js {
            get {
                return ResourceManager.GetString("jquery_fittext_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/jquery-2.1.4.min.js.
        /// </summary>
        internal static string jquery_min_js {
            get {
                return ResourceManager.GetString("jquery_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/loader.css.
        /// </summary>
        internal static string loader_css {
            get {
                return ResourceManager.GetString("loader_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/loader.js.
        /// </summary>
        internal static string loader_js {
            get {
                return ResourceManager.GetString("loader_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/login/login.css.
        /// </summary>
        internal static string login_css {
            get {
                return ResourceManager.GetString("login_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/login/loginForm.js.
        /// </summary>
        internal static string loginForm_js {
            get {
                return ResourceManager.GetString("loginForm_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/marked-0.3.5.min.js.
        /// </summary>
        internal static string marked_min_js {
            get {
                return ResourceManager.GetString("marked_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/me.jpg.
        /// </summary>
        internal static string me_jpg {
            get {
                return ResourceManager.GetString("me_jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/login/particles/app.js.
        /// </summary>
        internal static string particles_app_js {
            get {
                return ResourceManager.GetString("particles_app_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/particles-2.0.0.min.js.
        /// </summary>
        internal static string particles_min_js {
            get {
                return ResourceManager.GetString("particles_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/login/particles/style.css.
        /// </summary>
        internal static string particles_style_css {
            get {
                return ResourceManager.GetString("particles_style_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/partner.png.
        /// </summary>
        internal static string partner_png {
            get {
                return ResourceManager.GetString("partner_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/respond-1.4.2.min.js.
        /// </summary>
        internal static string respond_min_js {
            get {
                return ResourceManager.GetString("respond_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/login/translator.js.
        /// </summary>
        internal static string translator_js {
            get {
                return ResourceManager.GetString("translator_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/login/trianglify.css.
        /// </summary>
        internal static string trianglify_css {
            get {
                return ResourceManager.GetString("trianglify_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/trianglify-0.4.0.min.js.
        /// </summary>
        internal static string trianglify_min_js {
            get {
                return ResourceManager.GetString("trianglify_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/login/TrianglifyCreator.js.
        /// </summary>
        internal static string trianglifyCreator_js {
            get {
                return ResourceManager.GetString("trianglifyCreator_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/local_resources/wow-1.1.2.min.js.
        /// </summary>
        internal static string wow_min_js {
            get {
                return ResourceManager.GetString("wow_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/xomorod.css.
        /// </summary>
        internal static string xomorod_css {
            get {
                return ResourceManager.GetString("xomorod_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/xomorod-dialog.css.
        /// </summary>
        internal static string xomorod_dialog_css {
            get {
                return ResourceManager.GetString("xomorod_dialog_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to js/xomorod.js.
        /// </summary>
        internal static string xomorod_js {
            get {
                return ResourceManager.GetString("xomorod_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/xomorod.svg.
        /// </summary>
        internal static string xomorod_svg {
            get {
                return ResourceManager.GetString("xomorod_svg", resourceCulture);
            }
        }
    }
}
