//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xomorod.Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xomorod.Demo.Resources.localization", typeof(localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        internal static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realize your ideas in the form of Android apps at the least possible time.
        /// </summary>
        internal static string AndroidService {
            get {
                return ResourceManager.GetString("AndroidService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        internal static string Apple {
            get {
                return ResourceManager.GetString("Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build multi-platform applications with Xamarin technology for iOS and other platforms.
        /// </summary>
        internal static string AppleService {
            get {
                return ResourceManager.GetString("AppleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Your Service.
        /// </summary>
        internal static string AtYourServie {
            get {
                return ResourceManager.GetString("AtYourServie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Out More.
        /// </summary>
        internal static string FindOutMore {
            get {
                return ResourceManager.GetString("FindOutMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Download at Xomorod!.
        /// </summary>
        internal static string FreeDownload {
            get {
                return ResourceManager.GetString("FreeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Get In Touch!.
        /// </summary>
        internal static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start your next project with us? That&apos;s great! Give us a call or send us an email and we will get back to you as soon as possible!.
        /// </summary>
        internal static string GetInTouchP {
            get {
                return ResourceManager.GetString("GetInTouchP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started!.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Download Now!.
        /// </summary>
        internal static string MoreDownload {
            get {
                return ResourceManager.GetString("MoreDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod Corporation has small software company to provide what you need in the field of web applications, Windows, Android and iOS. Most of the application on Xomorod are open source, free to download, and easy to use..
        /// </summary>
        internal static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve got what you need!.
        /// </summary>
        internal static string MoreInfoTitle {
            get {
                return ResourceManager.GetString("MoreInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolios.
        /// </summary>
        internal static string Portfolios {
            get {
                return ResourceManager.GetString("Portfolios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best of our products..
        /// </summary>
        internal static string PortfoliosTitle {
            get {
                return ResourceManager.GetString("PortfoliosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string RightToLeft {
            get {
                return ResourceManager.GetString("RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To contact the team members can follow them on social networks or via email if you communicate with them..
        /// </summary>
        internal static string TeamContact {
            get {
                return ResourceManager.GetString("TeamContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod company programmer and designers..
        /// </summary>
        internal static string TeamSubTitle {
            get {
                return ResourceManager.GetString("TeamSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Amazing Team.
        /// </summary>
        internal static string TeamTitle {
            get {
                return ResourceManager.GetString("TeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All software of Xomorod are supported for windows desktop and web platforms.
        /// </summary>
        internal static string WindowsService {
            get {
                return ResourceManager.GetString("WindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod.
        /// </summary>
        internal static string Xomorod {
            get {
                return ResourceManager.GetString("Xomorod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our broad tool-set enables us to partner with you to create and integrate custom solutions..
        /// </summary>
        internal static string XomorodService {
            get {
                return ResourceManager.GetString("XomorodService", resourceCulture);
            }
        }
    }
}
